name: For testing terraform scripts
on:

  pull_request:

       branches: [main]

  push:

       branches: [main]
jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::446963233070:role/github-oidc-role
        aws-region: us-east-1
    #- name: Copy files to the test website with the AWS CLI
     # run: |
      #  aws s3 sync . s3://testlogbuckett
    - name: Installing terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.5

    - name: Terraform Init
      id: init
      run: |
        cd myterraform/
        terraform init

    - name: Terraform Plan
      id: plan
      run: | 
        cd myterraform/
        terraform plan
      continue-on-error: true

    - name: Terraform Apply
      id: apply
      run: | 
        cd myterraform/
        terraform apply -auto-approve